### ISSUE TITLE
How to use l20n.php ?

### ISSUE THREAD

**Issue by SunboX** [texthtml/l20n.php#1]
See title, how do I use it :question:

**Comment by mathroc** [comment]
I guess a README.md is needed :) 

meanwhile you can take a look at https://github.com/texthtml/place for usage exemples (look for `l20n:id` & `l20n:data` in https://github.com/texthtml/place/blob/develop/src/index.html  and for `thL20N*` in https://github.com/texthtml/place/blob/develop/src/place.js )

**Comment by mathroc** [comment]
ow I made a mistake, i thought you were talking about https://github.com/texthtml/angularjs-l20n … This project is nowhere near been useful yet and I'm not working on it :/
If you're looking for a working l20n PHP library unfortunately I don't know any :(

**Comment by SunboX** [comment]
Thanks for your comments! :smile: I did find another PHP L20n lib that was very useful:
https://github.com/tisogawa/php-l20n/issues/1
